name: Release

on:
  workflow_dispatch:
  push:
     branches:
       - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'shamimice03'
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # https://github.com/actions/checkout
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18.0.0                      # https://semantic-release.gitbook.io/semantic-release/v/beta/extending/plugins-list
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
